
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int AND = 27;
  public static final int IDENT = 34;
  public static final int ELSE = 19;
  public static final int PLUS = 2;
  public static final int INT = 30;
  public static final int OR = 28;
  public static final int RPAREN = 8;
  public static final int EQUAL = 17;
  public static final int NOTEQUAL = 23;
  public static final int WHILE = 20;
  public static final int SEMI = 13;
  public static final int NOT = 29;
  public static final int RCURLY = 10;
  public static final int Q = 31;
  public static final int RETURN = 11;
  public static final int INTCONST = 33;
  public static final int REF = 32;
  public static final int IF = 18;
  public static final int LESSEQUAL = 21;
  public static final int LPAREN = 7;
  public static final int NIL = 15;
  public static final int CAST = 16;
  public static final int LARGER = 26;
  public static final int LCURLY = 9;
  public static final int ISEQUAL = 24;
  public static final int COMMA = 5;
  public static final int EOF = 0;
  public static final int LARGEEQUAL = 22;
  public static final int MINUS = 3;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int DOT = 6;
  public static final int MUT = 14;
  public static final int LESS = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "COMMA",
  "DOT",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "RETURN",
  "PRINT",
  "SEMI",
  "MUT",
  "NIL",
  "CAST",
  "EQUAL",
  "IF",
  "ELSE",
  "WHILE",
  "LESSEQUAL",
  "LARGEEQUAL",
  "NOTEQUAL",
  "ISEQUAL",
  "LESS",
  "LARGER",
  "AND",
  "OR",
  "NOT",
  "INT",
  "Q",
  "REF",
  "INTCONST",
  "IDENT"
  };
}

