
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int AND = 23;
  public static final int IDENT = 27;
  public static final int ELSE = 16;
  public static final int PLUS = 2;
  public static final int OR = 24;
  public static final int RPAREN = 7;
  public static final int INT = 13;
  public static final int EQUAL = 14;
  public static final int NOTEQUAL = 19;
  public static final int SEMI = 12;
  public static final int NOT = 25;
  public static final int RCURLY = 9;
  public static final int RETURN = 10;
  public static final int INTCONST = 26;
  public static final int IF = 15;
  public static final int LESSEQUAL = 17;
  public static final int LPAREN = 6;
  public static final int LARGER = 22;
  public static final int LCURLY = 8;
  public static final int ISEQUAL = 20;
  public static final int COMMA = 5;
  public static final int EOF = 0;
  public static final int LARGEEQUAL = 18;
  public static final int MINUS = 3;
  public static final int PRINT = 11;
  public static final int error = 1;
  public static final int LESS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "RETURN",
  "PRINT",
  "SEMI",
  "INT",
  "EQUAL",
  "IF",
  "ELSE",
  "LESSEQUAL",
  "LARGEEQUAL",
  "NOTEQUAL",
  "ISEQUAL",
  "LESS",
  "LARGER",
  "AND",
  "OR",
  "NOT",
  "INTCONST",
  "IDENT"
  };
}

